language: cpp
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
#    - libsdl1.2-dev
    - zlib1g-dev
    - gcc-4.8
    - g++-4.8
before_script:
    - export CXX=g++-4.8
# Build and test both in release and debug to ensure both works fine
script: 
 - make
 - make unit_test
 - make clean
 - make debug
