language: cpp
#To uncomment in case a core occurs:
sudo: required
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - libsdl1.2-dev
    - zlib1g-dev
    - gcc-4.8
    - g++-4.8
#To uncomment in case a core occurs:
    - gdb
before_script:
    - export CXX=g++-4.8
# Build and test both in release and debug to ensure both works fine
script: 
#To uncomment in case a core occurs:
 - ulimit -c unlimited
 - sudo sysctl kernel.core_pattern=core
 - make
 - make unit_test
 - make clean
#To uncomment in case a core occurs:
 - rm -f ./core
 - make debug
#To uncomment in case a core occurs:
 - find ./ -name 'core*'
 - for i in $(find ./ -name 'core*' -print); do gdb kalenji_reader $i -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
