
GL_FUNC(void,glBegin,(GLenum))
GL_FUNC(void,glBindTexture,(GLenum,GLuint))
GL_FUNC(void,glBlendFunc,(GLenum,GLenum))
GL_FUNC(void,glColor4f,(GLfloat,GLfloat,GLfloat,GLfloat))
GL_FUNC(void,glDisable,(GLenum cap))
GL_FUNC(void,glEnable,(GLenum cap))
GL_FUNC(void,glEnd,(void))
GL_FUNC(void,glGenTextures,(GLsizei n, GLuint *textures))
GL_FUNC(void,glDeleteTextures,(GLsizei n, GLuint *textures))
GL_FUNC(void,glGetIntegerv,(GLenum pname, GLint *params))
GL_FUNC(const GLubyte *,glGetString,(GLenum name))
GL_FUNC(void,glLoadIdentity,(void))
GL_FUNC(void,glMatrixMode,(GLenum mode))
GL_FUNC(void,glOrtho,(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))
GL_FUNC(void,glTexCoord2f,(GLfloat s, GLfloat t))
GL_FUNC(void,glTexImage2D,(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels))
GL_FUNC(void,glTexParameteri,(GLenum target, GLenum pname, GLint param))
GL_FUNC(void,glTexSubImage2D,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))
GL_FUNC(void,glVertex2i,(GLint x, GLint y))
GL_FUNC(void,glViewport,(GLint x, GLint y, GLsizei width, GLsizei height))
GL_FUNC(GLboolean,glIsTexture,( GLuint texture ))
GL_FUNC(void,glTexEnvf,(GLenum, GLenum, GLfloat))
GL_FUNC_OPTIONAL(void,glColorTableEXT, (GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *))
GL_FUNC_OPTIONAL(void,glActiveTextureARB, (GLenum))
GL_FUNC_OPTIONAL(void,glMultiTexCoord2fARB, (GLenum,GLfloat,GLfloat))

